### ISSUE TITLE
Import Kotlin

### ISSUE THREAD

**Issue by alvince** [yellowbluesky/PixivforMuzei3#108]
Why not program with Kotlin.
Is there any reason that code by Java only?

Could we import Kotlin for features or refactor?

**Comment by yellowbluesky** [comment]
Good question :) 

I did try using the conversion tool to convert to Kotlin a short while ago, but it result required a lot more work and time investment that I didn't have. 

I'll try it again soon based on your suggestion, 

Initially I started developing this app as a way to learn about developing an Android app. To limit the number of new things I'd have to learn at the same time I picked Java because:

* It is a language I already know how to use 

* It's similar to C / C++, languages I use at my workplace

**Comment by alvince** [comment]
> Good question :)
> 
> I did try using the conversion tool to convert to Kotlin a short while ago, but it result required a lot more work and time investment that I didn't have.
> 
> I'll try it again soon based on your suggestion,
> 
> Initially I started developing this app as a way to learn about developing an Android app. To limit the number of new things I'd have to learn at the same time I picked Java because:
> 
> * It is a language I already know how to use
> * It's similar to C / C++, languages I use at my workplace

Ok, I got it.

I will transform it to Kotlin on a separate branch when i am free, if u accept it  :)

**Comment by yellowbluesky** [comment]
You're welcome to refactor this project into Kotlin

I'm plannig on starting a Kotlin refactor myself soon, as I want to use this as an opportunity to learn
