### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by yellowbluesky** [yellowbluesky/PixivforMuzei3#122]
A user requested that this feature

Notes:
Almost all of the UI use the Preferences library. I picked this library because it allowed for fast UI creation allowing me to focus on the business logic.
However, it does not support dark mode.

I'll need to recreate the UI from scratch, and all associated logic, in order to implement a dark mode.

I'll try to work on this, but it's at a low priority now.

**Comment by jasonkhanlar** [comment]
Oooh, also, I recently switched my phone to dark mode in the Android 6.0 settings. My specific phone did NOT have it, because F to Verizon, but, thanks to https://www.xda-developers.com/enable-dark-themes-some-android-apps-older-android-versions/

```adb shell settings put secure ui_night_mode 1```

I was able to enable the setting, and now a lot of the apps appear in dark mode without even the apps being programmed for it, since it seems the theming was handled by system functions.

**Comment by yellowbluesky** [comment]
I'll test this later, I am currently a little busy

**Comment by yellowbluesky** [comment]
Good news. I have revisited this, and I've got night mode working

**Comment by yellowbluesky** [comment]
Feature added in 2a82a62d4d88c62e2addf9da7cf46c3a67234e2c

Translations pending

**Comment by yellowbluesky** [comment]
Released to production in version 3.3.0
