### ISSUE TITLE
Stop storing images to private storage when store into public storage is enabled

### ISSUE THREAD

**Issue by KawaiiZapic** [yellowbluesky/PixivforMuzei3#137]
I want to review every images downloaded so I won't enable clear cache,and I wanna to share images to my friends so I enabled store image to public storage.
Is there any problem to read images from public storage directly?  
I think is a good way to reduce storage space, or there are a lot of duplicate images in my device.

**Comment by yellowbluesky** [comment]
Hi there, thanks for raising/suggesting this issue. I'll have a look at things now

**Comment by yellowbluesky** [comment]
How downloadFile() currently works: https://github.com/yellowbluesky/PixivforMuzei3/blob/0e1a7c2ad2089596c9b46df50dfcd6975a1100a7/app/src/main/java/com/antony/muzei/pixiv/provider/PixivArtWorker.kt#L227

1. Download the file first to an internal location. This always happens
2. Check if the user has selected the option to save the image to external storage
3. Do some miscellaneous checks, then copy the image from the internal storage to external storage.

I can change the code so that it only ever downloads to one place.
I don't think it's a problem for images on the external storage to be deleted while they're still backing Artworks, Muzei already handles this gracefully.

I'll try this out and will let you know of the result

**Comment by yellowbluesky** [comment]
Behaviour changed. Assuming a situation where "Store into external storage is checked"

Previously, copies of the artwork could be found at:

- /data/data/com.antony.muzei.pixiv
- /storage/emulated/0/Android/data/com.antony.muzei.pixiv
- /storage/emulated/0/Pictures/PixivForMuzei3

Now:

- /data/data/com.antony.muzei.pixiv
- /storage/emulated/0/Pictures/PixivForMuzei3

So far, I've removed one copy.

I'll see if I can also get rid of the artwork copy at /data/data/com.antony.muzei.pixiv

**Comment by yellowbluesky** [comment]
Feature released to production.

Commit added in 8d4e975fb12cfc985e464b40bf27a975aee59786

The copy made to /data/data/com.antony.muzei.pixiv cannot be avoided, this is somethign that Muzei does
